import 'package:flutter/material.dart';

List<String> listOfStations=
[
"AIIMS",
"Adarsh Nagar",
"Airport",
"Akshardham",
"Anand Vihar",
"Arjan Garh",
"Arthala",
"Ashok Park Main",
"Ashram",
"Azadpur",
"Badarpur Border",
"Badkhal Mor",
"Bahadurgarh City",
"Barakhambha Road",
"Bata Chowk",
"Bhikaji Cama Place",
"Botanical Garden",
"Brigadier Hoshiyar Singh",
"Central Secretariat",
"Chandni Chowk",
"Chawri Bazar",
"Chhatarpur",
"Chirag Delhi",
"Civil Lines",
"Dabri Mor-Janakpuri South",
"Dashrath Puri",
"Delhi Aerocity",
"Delhi Cantonment",
"Delhi Gate",
"Dhaula Kuan",
"Dilshad Garden",
"Durgabai Deshmukh South Campus",
"Dwarka",
"Dwarka Mor",
"Dwarka Sector 10",
"Dwarka Sector 11",
"Dwarka Sector 12",
"Dwarka Sector 13",
"Dwarka Sector 14",
"Dwarka Sector 21",
"Dwarka Sector 8",
"Dwarka Sector 9",
"ESI Hospital",
"East Azad Nagar",
"East Vinod Nagar – Mayur Vihar-II",
"Escorts Mujesar",
"GTB Nagar",
"Ghevra",
"Ghitorni",
"Gokulpuri",
"Golf Course",
"Govind Puri",
"Greater Kailash",
"Green Park",
"Guru Dronacharya",
"HUDA City Centre",
"Haiderpur",
"Harkesh Nagar",
"Hauz Khas",
"Hazrat Nizamuddin",
"Hindon",
"IFFCO Chowk",
"IIT Delhi",
"INA",
"IP Extension",
"ITO",
"Inderlok",
"Indraprastha",
"Jaffrabad",
"Jahangirpuri",
"Jama Masjid",
"Jamia Millia Islamia",
"Janakpuri East",
"Janakpuri West",
"Jangpura",
"Janpath",
"Jasola Apollo",
"Jasola Vihar Shaheen Bagh",
"Jawaharlal Nehru Stadium",
"Jhandewalan",
"Jhilmil",
"Johari Enclave",
"Jor Bagh",
"Kailash Colony",
"Kalindi Kunj",
"Kalkaji Mandir",
"Kanhaiya Nagar",
"Karkarduma",
"Karkarduma Court",
"Karol Bagh",
"Kashmere Gate",
"Kaushambi",
"Keshav Puram",
"Khan Market",
"Kirti Nagar",
"Kohat Enclave",
"Krishna Nagar",
"Lajpat Nagar",
"Lal Qila",
"Laxmi Nagar",
"Lok Kalyan Marg",
"MG Road",
"Madipur",
"Maharaja Surajmal Stadium",
"Majlis Park",
"Major Mohit Sharma",
"Malviya Nagar",
"Mandawali – West Vinod Nagar",
"Mandi House",
"Mansarovar Park",
"Maujpur-Babarpur",
"Mayapuri",
"Mayur Vihar - I",
"Mayur Vihar Extension",
"Mayur Vihar Pocket I",
"Mewala Maharajpur",
"Model Town",
"Mohan Estate",
"Mohan Nagar",
"Moolchand",
"Moti Nagar",
"Mundka",
"Mundka Industrial Area",
"Munirka",
"NHPC Chowk",
"Nangloi",
"Nangloi Railway station",
"Naraina Vihar",
"Nawada",
"Neelam Chowk Ajronda",
"Nehru Enclave",
"Nehru Place",
"Netaji Subhash Place",
"New Ashok Nagar",
"New Delhi",
"Nirman Vihar",
"Noida City Centre",
"Noida Electronic City",
"Noida Sector 15",
"Noida Sector 16",
"Noida Sector 18",
"Noida Sector 34",
"Noida Sector 52",
"Noida Sector 59",
"Noida Sector 61",
"Noida Sector 62",
"Okhla Bird Sanctuary",
"Okhla NSIC",
"Okhla Vihar",
"Old Faridabad",
"Palam",
"Panchsheel Park",
"Pandit Shree Ram Sharma",
"Paschim Vihar East",
"Paschim Vihar West",
"Patel Chowk",
"Patel Nagar",
"Peera Garhi",
"Pitam Pura",
"Pragati Maidan",
"Pratap Nagar",
"Preet Vihar",
"Pul Bangash",
"Punjabi Bagh"
"Punjabi Bagh West",
"Qutub Minar",
"R.K.Puram",
"Raj Bagh",
"Raja Nahar Singh",
"Rajdhani Park",
"Rajendra Place",
"Rajiv Chowk",
"Rajouri Garden",
"Ramakrishna Ashram Marg",
"Ramesh Nagar",
"Rithala",
"Rohini East",
"Rohini Sector 18",
"Rohini West",
"Sadar Bazaar Cantonment",
"Saket",
"Samaypur Badli",
"Sant Surdas",
"LSarai",
"Sarojini Nagar",
"Satguru Ramsingh Marg",
"Sector 28",
"Seelampur",
"Shadipur",
"Shahdara",
"Shaheed Nagar",
"Shaheed Sthal",
"Shakurpur",
"Shalimar Bagh",
"Shankar Vihar",
"Shastri Nagar",
"Shastri Park",
"Shiv Vihar",
"Shivaji Park",
"Shivaji Stadium",
"Shyam Park",
"Sikandarpur",
"Sir Vishweshwaraiah Moti Bagh",
"South Extension",
"Subhash Nagar",
"Sukhdev Vihar",
"Sultanpur",
"Tagore Garden",
"Terminal 1-IGI Airport",
"Tikri Border",
"Tikri Kalan",
"Tilak Nagar",
"Tis Hazari",
"Trilokpuri Sanjay Lake",
"Tughlakabad Station",
"Udyog Bhawan",
"Udyog Nagar",
"Uttam Nagar East",
"Uttam Nagar West",
"Vaishali",
"Vasant Vihar",
"Vidhan Sabha",
"Vinobapuri",
"Vishwa Vidyalaya",
"Welcome",
"Yamuna Bank",
"Noida Sector 51",
"Noida Sector 50",
"Noida Sector 76",
"Noida Sector 101",
"Noida Sector 81",
"NSEZ",
"Noida Sector 83",
"Noida Sector 137",
"Noida Sector 142",
"Noida Sector 143",
"Noida Sector 144",
"Noida Sector 145",
"Noida Sector 146",
"Noida Sector 147",
"Noida Sector 148",
"Knowledge Park II",
"Pari Chowk",
"Alpha 1",
"Delta 1",
"GNIDA Office",
"Depot",
];